runtime: go
api_version: go1

handlers:
- url: /stylesheets
  static_dir: static/stylesheets
  http_headers:
    Vary: Accept-Encoding
- url: /js
  static_dir: static/js
  http_headers:
    Vary: Accept-Encoding
    Content-Type: application/javascript
    Cache-Control: max-age=3600
    ETag: "c54b11e7140"
- url: /musicbox
  static_files: static/musicbox.html
  upload: static/musicbox.html
  http_headers:
    Vary: Accept-Encoding
- url: /.*
  script: _go_app
